services:
  # PostgreSQL for Analytics / dbt
  postgres_analytics:
    image: postgres:15-alpine
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql-scripts/init-warehouse.sql:/docker-entrypoint-initdb.d/init.sql

  # PostgreSQL for Airflow metadata
  postgres_airflow:
    image: postgres:15-alpine
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: ${AIRFLOW_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB}
    ports:
      - "${AIRFLOW_PORT}:5432"
    volumes:
      - airflow_dbdata:/var/lib/postgresql/data

  # Airflow webserver
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres_airflow:5432/${AIRFLOW_DB}
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      DBT_PROFILES_DIR: /opt/airflow/dbt/dbt_project
      PYTHONPATH: /opt/airflow
      BASE_DIR: /opt/airflow/TPCH
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres_analytics
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres_airflow
      - postgres_analytics
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./ingestion:/opt/airflow/ingestion
      - airflow_logs:/opt/airflow/logs
      - ./TPCH:/opt/airflow/TPCH
    command: ["airflow", "webserver"]

  # Airflow scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres_airflow:5432/${AIRFLOW_DB}
      DBT_PROFILES_DIR: /opt/airflow/dbt/dbt_project
      PYTHONPATH: /opt/airflow
      BASE_DIR: /opt/airflow/TPCH
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres_analytics
      POSTGRES_PORT: 5432
    depends_on:
      - postgres_airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./ingestion:/opt/airflow/ingestion
      - airflow_logs:/opt/airflow/logs
      - ./TPCH:/opt/airflow/TPCH
    command: ["airflow", "scheduler"]

  # FastAPI app
  fastapi:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
      - ./dbt/dbt_project:/dbt/dbt_project
    environment:
      POSTGRES_HOST: postgres_analytics
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres_analytics

  # Metabase DB
  metabase_db:
    image: postgres:15-alpine
    container_name: metabase_db
    restart: always
    environment:
      POSTGRES_DB: ${MB_DB}
      POSTGRES_USER: ${MB_USER}
      POSTGRES_PASSWORD: ${MB_PASSWORD}
    volumes:
      - metabase_data:/var/lib/postgresql/data

  # Metabase
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB}
      MB_DB_PORT: ${MB_PORT}
      MB_DB_USER: ${MB_USER}
      MB_DB_PASS: ${MB_PASSWORD}
      MB_DB_HOST: metabase_db
    depends_on:
      - metabase_db

volumes:
  pgdata:
  airflow_dbdata:
  airflow_logs:
  metabase_data:
