services:
  postgres_analytics:
    image: postgres:15-alpine
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql-scripts/init-warehouse.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_airflow:
    image: postgres:15-alpine
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: ${AIRFLOW_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB}
    ports:
      - "${AIRFLOW_PORT}:5432"
    volumes:
      - airflow_dbdata:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres_airflow:5432/${AIRFLOW_DB}
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      DBT_PROFILES_DIR: /opt/airflow/dbt/dbt_project
    ports:
      - "8080:8080"
    depends_on:
      - postgres_airflow
      - postgres_analytics
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - airflow_logs:/opt/airflow/logs
    command: ["airflow", "webserver"]

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres_airflow:5432/${AIRFLOW_DB}
      DBT_PROFILES_DIR: /opt/airflow/dbt/dbt_project
    depends_on:
      - postgres_airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - airflow_logs:/opt/airflow/logs
    command: ["airflow", "scheduler"]

volumes:
  pgdata:
  airflow_dbdata:
  airflow_logs:
